{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuer.name }}
  labels:
    {{- include "democrm.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.clusterIssuer.name }}-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}