apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "democrm.fullname" . }}
  labels:
    {{- include "democrm.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.democrm.replicaCount }}
  selector:
    matchLabels:
      {{- include "democrm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "democrm.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.democrm.image.repository }}:{{ .Values.democrm.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.democrm.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        {{- if .Values.democrm.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.democrm.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.democrm.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.democrm.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.democrm.resources | nindent 10 }}
        env:
        - name: LOG_LEVEL
          value: {{ .Values.democrm.config.logLevel | quote }}
        - name: PERSISTENCE
          value: {{ .Values.democrm.config.persistence | quote }}
        {{- if .Values.communityOperator.enabled }}
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: {{ include "democrm.mongodbSecretName" . }}
              key: mongodb-uri
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}