apiVersion: v1
kind: Service
metadata:
  name: {{ include "democrm.fullname" . }}
  labels:
    {{- include "democrm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.democrm.service.type }}
  ports:
  - port: {{ .Values.democrm.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "democrm.selectorLabels" . | nindent 4 }}